version: '3.7'
services:
  server:
    build:
      context: ./server
    environment:
      NODE_ENV: development
    volumes:
     - ./server/src:/var/www/dashboard/src
     - ./server/config:/var/www/dashboard/config
    ports:
     - "9264:9264"
  client:
    build:
      context: ./client
    environment:
      NODE_ENV: development
    volumes:
     - ./client/src:/var/www/dashboard-client/src
  nginx:
    build:
      context: ./tools/nginx
    ports:
     - "8181:80"
    depends_on:
     - server
     - client
